### ISSUE TITLE
Utils.ShowHintSurvivors/Infected/All

### ISSUE THREAD

**Issue by PeatearB** [L4D2Scripters/vslib#2]
I think there's a comma missing on these between binding and pulsating.

survivor.ShowHint( text, duration, icon, color, binding pulsating, alphapulse, shaking );
infected.ShowHint( text, duration, icon, color, binding pulsating, alphapulse, shaking );
player.ShowHint( text, duration, icon, color, binding pulsating, alphapulse, shaking );

**Comment by Rayman1103** [comment]
This issue was previously fixed.
