### ISSUE TITLE
EasyLogic:Ondeath Event problem.

### ISSUE THREAD

**Issue by guljam** [L4D2Scripters/vslib#3]
hello i really enjoy with this library! from korea.

[Ondeath function(Player Death event)] problem is include common zombie's death.
well. i don't know this is problem or not.

but i think, 1.5version or sourcemod's hook event is not include common zombie's death in Player_death event.

it seems overlap "infected death" event.sorry bad english. please check. OnDeath function.

thankyou

**Comment by guljam** [comment]
PS. and Infected_death and Infected_Hurt event not effect with Bride Witch.

**Comment by Rayman1103** [comment]
Having common infected trigger for player_death is normal, there was a previous bug that prevented them from properly triggering the function.

Damaging the Witch Bride properly triggers infected_hurt for me, at least in the current version of VSLib.
