### ISSUE TITLE
Utils.nut  1547line. error.

### ISSUE THREAD

**Issue by guljam** [L4D2Scripters/vslib#4]
survivor.ShowHint( text, duration, icon, color, [[[[[binding pulsating]]]]], alphapulse, shaking );

-->survivor.ShowHint( text, duration, icon, color, [[[[[binding, pulsating]]]]], alphapulse, shaking );

**Comment by Rayman1103** [comment]
Thanks this was fixed a while back, I just never closed the Issue.
