### ISSUE TITLE
Netprops Error

### ISSUE THREAD

**Issue by guljam** [L4D2Scripters/vslib#5]
hello  i'm korean, very poor english. sorry.

i try use vslib 4.0,
typing only IncludeScript("vslib")

error in console,

i can't anything with this version

i wonder NETPROP is like sourcemod's GetEntProps function?
can i adjust m_iclip or m_ihealth of player entity?

---

AN ERROR HAS OCCURED [the index 'NetProps' does not exist]

CALLSTACK
*FUNCTION [GetNetPropInt()] c:/program files (x86)/steam/steamapps/common/left 4 dead 2/left4dead2/scripts/vscripts/VSLib/Entity.nut line [473]
*FUNCTION [unknown()] c:/program files (x86)/steam/steamapps/common/left 4 dead 2/left4dead2/scripts/vscripts/VSLib/EasyLogic.nut line [1850]
*FUNCTION [__RunEventCallbacks()] unnamed line [211]
*FUNCTION [__RunGameEventCallbacks()] unnamed line [218]

LOCALS
[prop] "m_iTeamNum"
[this] INSTANCE
[_id] 1
[ents] TABLE
[params] TABLE
[this] TABLE
[funcName] "OnGameEvent_player_spawn"
[idx] 0
[useTable] TABLE
[bWarnIfMissing] false
[globalTableName] "GameEventCallbacks"
[prefix] "OnGameEvent_"
[params] TABLE
[event] "player_spawn"
[this] TABLE
[params] TABLE
[event] "player_spawn"
[this] TABLE

AN ERROR HAS OCCURED [the index 'NetProps' does not exist]

CALLSTACK
*FUNCTION [GetNetPropInt()] c:/program files (x86)/steam/steamapps/common/left 4 dead 2/left4dead2/scripts/vscripts/VSLib/Entity.nut line [473]
*FUNCTION [unknown()] c:/program files (x86)/steam/steamapps/common/left 4 dead 2/left4dead2/scripts/vscripts/VSLib/EasyLogic.nut line [1868]
*FUNCTION [__RunEventCallbacks()] unnamed line [211]
*FUNCTION [__RunGameEventCallbacks()] unnamed line [218]

LOCALS
[prop] "m_iTeamNum"
[this] INSTANCE
[_id] 2
[ents] TABLE
[params] TABLE
[this] TABLE
[funcName] "OnGameEvent_player_first_spawn"
[idx] 0
[useTable] TABLE
[bWarnIfMissing] false
[globalTableName] "GameEventCallbacks"
[prefix] "OnGameEvent_"
[params] TABLE
[event] "player_first_spawn"
[this] TABLE
[params] TABLE
[event] "player_first_spawn"
[this] TABLE

AN ERROR HAS OCCURED [the index 'NetProps' does not exist]

CALLSTACK
*FUNCTION [GetNetPropInt()] c:/program files (x86)/steam/steamapps/common/left 4 dead 2/left4dead2/scripts/vscripts/VSLib/Entity.nut line [473]
*FUNCTION [unknown()] c:/program files (x86)/steam/steamapps/common/left 4 dead 2/left4dead2/scripts/vscripts/VSLib/EasyLogic.nut line [1847]
*FUNCTION [__RunEventCallbacks()] unnamed line [211]
*FUNCTION [__RunGameEventCallbacks()] unnamed line [218]

LOCALS
[prop] "m_iTeamNum"
[this] INSTANCE
[_id] 2
[ents] TABLE
[params] TABLE
[this] TABLE
[funcName] "OnGameEvent_player_spawn"
[idx] 0
[useTable] TABLE
[bWarnIfMissing] false
[globalTableName] "GameEventCallbacks"
[prefix] "OnGameEvent_"
[params] TABLE
[event] "player_spawn"
[this] TABLE
[params] TABLE
[event] "player_spawn"
[this] TABLE

AN ERROR HAS OCCURED [the index 'NetProps' does not exist]

CALLSTACK
*FUNCTION [GetNetPropInt()] c:/program files (x86)/steam/steamapps/common/left 4 dead 2/left4dead2/scripts/vscripts/VSLib/Entity.nut line [473]
*FUNCTION [unknown()] c:/program files (x86)/steam/steamapps/common/left 4 dead 2/left4dead2/scripts/vscripts/VSLib/EasyLogic.nut line [1868]
*FUNCTION [__RunEventCallbacks()] unnamed line [211]
*FUNCTION [__RunGameEventCallbacks()] unnamed line [218]

LOCALS
[prop] "m_iTeamNum"
[this] INSTANCE
[_id] 3
[ents] TABLE
[params] TABLE
[this] TABLE
[funcName] "OnGameEvent_player_first_spawn"
[idx] 0
[useTable] TABLE
[bWarnIfMissing] false
[globalTableName] "GameEventCallbacks"
[prefix] "OnGameEvent_"
[params] TABLE
[event] "player_first_spawn"
[this] TABLE
[params] TABLE
[event] "player_first_spawn"
[this] TABLE

AN ERROR HAS OCCURED [the index 'NetProps' does not exist]

CALLSTACK
*FUNCTION [GetNetPropInt()] c:/program files (x86)/steam/steamapps/common/left 4 dead 2/left4dead2/scripts/vscripts/VSLib/Entity.nut line [473]
*FUNCTION [unknown()] c:/program files (x86)/steam/steamapps/common/left 4 dead 2/left4dead2/scripts/vscripts/VSLib/EasyLogic.nut line [1847]
*FUNCTION [__RunEventCallbacks()] unnamed line [211]
*FUNCTION [__RunGameEventCallbacks()] unnamed line [218]

LOCALS
[prop] "m_iTeamNum"
[this] INSTANCE
[_id] 3
[ents] TABLE
[params] TABLE
[this] TABLE
[funcName] "OnGameEvent_player_spawn"
[idx] 0
[useTable] TABLE
[bWarnIfMissing] false
[globalTableName] "GameEventCallbacks"
[prefix] "OnGameEvent_"
[params] TABLE
[event] "player_spawn"
[this] TABLE
[params] TABLE
[event] "player_spawn"
[this] TABLE

AN ERROR HAS OCCURED [the index 'NetProps' does not exist]

CALLSTACK
*FUNCTION [GetNetPropInt()] c:/program files (x86)/steam/steamapps/common/left 4 dead 2/left4dead2/scripts/vscripts/VSLib/Entity.nut line [473]
*FUNCTION [unknown()] c:/program files (x86)/steam/steamapps/common/left 4 dead 2/left4dead2/scripts/vscripts/VSLib/EasyLogic.nut line [1868]
*FUNCTION [__RunEventCallbacks()] unnamed line [211]
*FUNCTION [__RunGameEventCallbacks()] unnamed line [218]

LOCALS
[prop] "m_iTeamNum"
[this] INSTANCE
[_id] 4
[ents] TABLE
[params] TABLE
[this] TABLE
[funcName] "OnGameEvent_player_first_spawn"
[idx] 0
[useTable] TABLE
[bWarnIfMissing] false
[globalTableName] "GameEventCallbacks"
[prefix] "OnGameEvent_"
[params] TABLE
[event] "player_first_spawn"
[this] TABLE
[params] TABLE
[event] "player_first_spawn"
[this] TABLE

AN ERROR HAS OCCURED [the index 'NetProps' does not exist]

CALLSTACK
*FUNCTION [GetNetPropInt()] c:/program files (x86)/steam/steamapps/common/left 4 dead 2/left4dead2/scripts/vscripts/VSLib/Entity.nut line [473]
*FUNCTION [unknown()] c:/program files (x86)/steam/steamapps/common/left 4 dead 2/left4dead2/scripts/vscripts/VSLib/EasyLogic.nut line [1847]
*FUNCTION [__RunEventCallbacks()] unnamed line [211]
*FUNCTION [__RunGameEventCallbacks()] unnamed line [218]

LOCALS
[prop] "m_iTeamNum"
[this] INSTANCE
[_id] 4
[ents] TABLE
[params] TABLE
[this] TABLE
[funcName] "OnGameEvent_player_spawn"
[idx] 0
[useTable] TABLE
[bWarnIfMissing] false
[globalTableName] "GameEventCallbacks"
[prefix] "OnGameEvent_"
[params] TABLE
[event] "player_spawn"
[this] TABLE
[params] TABLE
[event] "player_spawn"
[this] TABLE

**Comment by Rayman1103** [comment]
Hey sorry for the very late response. The issue is because I probably synced changes that were only meant for the L4D2 Beta at that time. Regular L4D2 didn't recieve the NetProp functions until January 25th 2017. It'll work perfectly fine now.

And your right, NetProps are like Sourcemod's GetEntProps functions. You can adjust m_iClip1, m_iHealth, etc of entities.
